##### LEARNING_PARAMETER #######################################################################
batch_size                      = 64
##### CHECKPOINT_SETTING #######################################################################
unet_load_checkpoint_name       = "Saturation_decay_832"
load_checkpoint_name            = "Detection_decay2_46"
##### MODEL_PARAMETER ##########################################################################
past_size                       = 0
present_size                    = 1600
future_size                     = 0
shift_size                      = 800
sampling_rate                   = 16000
##### DATASET_PATH #############################################################################
train_source_path               = "/home/ubuntu/DATASET/VCTK_CLIP_dataset/train"
test_source_path                = "/home/ubuntu/DATASET/VCTK_CLIP_dataset/test"
valid_source_path               = "/home/ubuntu/DATASET/VCTK_CLIP_dataset/valid"
train_target_path               = "/home/ubuntu/DATASET/VCTK_dataset/train"
test_target_path                = "/home/ubuntu/DATASET/VCTK_dataset/test"
valid_target_path               = "/home/ubuntu/DATASET/VCTK_dataset/valid"
